version: "3.1"
services:

    db:
      image: mysql:5.7
      restart: always
      environment:
          MYSQL_DATABASE: database
          MYSQL_USER: database
          MYSQL_PASSWORD: hackme
          MYSQL_RANDOM_ROOT_PASSWORD: '1'
      volumes:
          - db:/var/lib/mysql
          - ./mysql-dump:/docker-entrypoint-initdb.d
          - ./mysql-backup:/mysql-backup

    webserver:
      image: nginx:alpine
      restart: always
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      image: rojen/php7.4-fpm
      restart: always
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

volumes:
  db:
